---
apiVersion: v1
kind: Service
metadata:
  name: likes-api
  labels:
    app: likes-api
spec:
  ports:
    - port: 10000
      name: grpc
      targetPort: 10000
  selector:
    app: likes-api
  type: LoadBalancer
